Add database
DmPertsev/java-filmorate pull request #3
Opened 2023-08-20 14:33 UTC by DmPertsev

Спринт 11.

Добавление базы данных.
Жанры, дружба, лайки

2023-08-20 17:59 UTC, FanaticFiz requested changes
Финальный комментарий на Я.Практикуме

2023-08-20 17:59 UTC, FanaticFiz commented on src/main/java/ru/yandex/practicum/filmorate/exception/ValidationException.java
> +    public ValidationException(String message) {
Это частный случай `BadRequest` - который у тебя уже есть.

2023-08-20 17:59 UTC, FanaticFiz commented on src/main/java/ru/yandex/practicum/filmorate/service/FilmService.java
> +    private static int counter = 1;
Что за счетчик в сервисе??

Все теперь идентификаторы раздает база данных.

2023-08-20 17:59 UTC, FanaticFiz commented on src/main/java/ru/yandex/practicum/filmorate/service/FilmService.java
> +    public void validateReleaseDate(Film film, String text) {
Валидация это работа контроллера.

2023-08-20 17:59 UTC, FanaticFiz commented on src/main/java/ru/yandex/practicum/filmorate/storage/FilmStorage.java
> +    Collection<Film> findPopularFilms(Integer count);
List вместо Collection

2023-08-20 17:59 UTC, FanaticFiz commented on src/main/java/ru/yandex/practicum/filmorate/storage/UserStorage.java
> +    User findById(Integer id);
При выборке одиночных объектов из хранилища, полезно использовать Optional.

Это поможет писать удобный код в функциональном стиле в сервисах и с него удобно начать погружение в мир функциональщины.

2023-08-20 17:59 UTC, FanaticFiz commented on src/main/java/ru/yandex/practicum/filmorate/storage/dao/FilmDbStorage.java
> +    private final GenreService genreService;
Нельзя из хранилища использовать сервисы.
Наоборот сервисы используют хранилища и соседние сервисы.

2023-08-20 17:59 UTC, FanaticFiz commented on src/main/java/ru/yandex/practicum/filmorate/storage/dao/FilmDbStorage.java
> +    private Film makeFilm(ResultSet resultSet) throws SQLException {
Тут нужно быть аккуратнее!

Вот так в лоб нельзя делать в данном случае!
Давай поясню...
пусть у нас есть 100 фильмов... а у каждого из них есть жанры
для того чтобы собрать всё в одно и отдать при запросе нам нужно:

- достать все фильмы
- и все жанры к ним

Если делать "в лоб" то приходиться к каждому из 100-а фильмов отдельным запросом доставать еще и жанры...
получается ОДИН запрос на получение всех 100 фильмов и еще 100 запросов чтобы к каждому фильму подтянуть жанры....

Это называется проблема `N+1`
Чтобы её избежать мы должны заморочиться и в итоге приходим к всего ДВУМ запросам, вместо 101 !

Первый запрос на все фильмы, второй на все жанры для этих фильмов.

И все эти манипуляции следует выполнять в сервисе.

2023-08-22 18:03 UTC, FanaticFiz requested changes
Финальный комментарий на Я.Практикуме

2023-08-22 18:03 UTC, FanaticFiz commented on src/main/java/ru/yandex/practicum/filmorate/controller/FilmController.java
> +    public Optional<Film> create(@Valid @RequestBody Film film) {
`Optional` не должен был просочиться сюда.

Смысл в чем.
У нас есть неопределенность - есть объект в базе или нет.
Вот поэтому у `dao` метод должен возвращать `Optional<Film> findById`

Кто у нас пользуется классами `dao`? Сервисы...
Из сервиса мы дергаем метод `dao` и понимаем есть объект или нет.
Если есть возвращаем, если нет кидаем исключение.
Т.е. уже в сервисе метод идет просто `Film getById()`

Ну и соответственно в контроллере тоже.

2023-08-22 18:03 UTC, FanaticFiz commented on src/main/java/ru/yandex/practicum/filmorate/service/FilmService.java
> +        Optional<Film> film = filmStorage.findById(filmId);
`filmStorage.findById(filmId)` вот к этой конструкции, она же возвращает Optional, можно использовать методы. 
Самый частый и тот который тебе нужен в данном случае это orElseThrow - имеется ввиду следующее. Ты типа или найди мне значение или брось исключение.

Вот попробуй его применить, найди примеры - их много.

2023-08-22 18:03 UTC, FanaticFiz commented on src/main/java/ru/yandex/practicum/filmorate/service/FilmService.java
> +    private Optional<Film> getFilmStored(final String supposedId) {
Что то совсем неправильно с идентификатором `supposedId`.
Зачем ты его сделал строкой и потом доблестно с этой строкой борешься??

Принимай его как число сразу в контроллере.

2023-08-22 18:03 UTC, FanaticFiz commented on src/main/java/ru/yandex/practicum/filmorate/service/FilmService.java
> +    private void validate(Film film) {
Валидацию нужно вынести в контроллер.

2023-08-22 18:03 UTC, FanaticFiz commented on src/main/java/ru/yandex/practicum/filmorate/service/FilmService.java
> +    private static int counter = 1;
Снова пишу что не должно быть счетчиков. 
Идентификатор выдаст база данных. Это должно быть автоинкрементное, ключевое поле в таблице. (У тебя оно так и работает)

2023-08-22 18:03 UTC, FanaticFiz commented on src/main/java/ru/yandex/practicum/filmorate/service/UserService.java
> +    public Optional<User> update(User user) {
В методах-действиях тоже не нужен Optional
Пока, аккуратно вводим его только для одного метода `findById` в хранилищах, и все.
Ты уже пошел не в ту степь.

2023-08-22 18:03 UTC, FanaticFiz commented on src/main/java/ru/yandex/practicum/filmorate/service/UserService.java
> +    void throwIfUserPrintWrongInfo(User user) {
Этот метод это валидация. Всё, где ты кидаешь исключение `BadRequestException` - это валидация. Должно быть в контроллере.

2023-08-22 18:03 UTC, FanaticFiz commented on src/main/java/ru/yandex/practicum/filmorate/service/UserService.java
> +        if (user.getName() == null) {
А вот этот if и логика тут - уже к валидации не относится.
Эта наша бизнес логика. Наши правила по которым мы задаем имя пользователя.
Это должно быть в сервисе.

2023-08-22 18:03 UTC, FanaticFiz commented on src/main/java/ru/yandex/practicum/filmorate/storage/dao/FilmDbStorage.java
> +    private final GenreService genreService;
Ты закрываешь вопрос без внесения изменений в код. 
Так делать нельзя. 
Поднимаю замечание заново.

У нас на проекте, например, стоит запрет на такое. Нельзя закрыть комментарий ревьюера без какого либо ответного комментария. Даже если с комментарием согласились и исправили - надо это явно подсветить.

2023-08-22 20:00 UTC, DmPertsev commented on src/main/java/ru/yandex/practicum/filmorate/service/UserService.java
> +        if (user.getName() == null) {
Как я понял из твоего коммента, это тут так и оставить? "это должно быть в сервисе" он и в нем

2023-08-22 20:05 UTC, FanaticFiz commented on src/main/java/ru/yandex/practicum/filmorate/service/UserService.java
> +        if (user.getName() == null) {
Да верно. Это оставить тут, валидацию перенести в контроллер.

2023-08-23 19:12 UTC, FanaticFiz approved these changes

2023-08-23 19:31 UTC, merged